import React from 'react'
import Index from './components/Views/Blog/Index'
import Head from 'next/head'

const Blog = () => {
  return (
    <>
      <Head>
        <title>Blog Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index />
    </>
  )
}

export default Blog